# Generated by Django 3.2.7 on 2021-11-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conteudo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titulo',
            new_name='title',
        ),
    ]
